# Create UPM packages for public OFFICIAL release

variables:
- template: config/settings.yml

jobs:
- job: UPMPublicRelease
  timeoutInMinutes: 30
  pool:
    name: On-Prem Unity
  steps:
  - template: templates/tasks/upmpackages.yml
    parameters:
      excludeBuildNumber: 1
  - task: PowerShell@2
    displayName: 'UPM packages to registry'
    inputs:
      targetType: filePath
      filePath: ./scripts/packaging/publishupmpackages.ps1
      arguments: >
        -PackageDirectory $(Build.ArtifactStagingDirectory)\build\upm\output
        -RegistryPath $(UpmRegistry)